
/* Drop Tables */

DROP TABLE CIP_ATTACHFILE CASCADE CONSTRAINTS;
DROP TABLE CIP_AUTHORITY_MEMBER CASCADE CONSTRAINTS;
DROP TABLE CIP_MENU_AUTHORITY CASCADE CONSTRAINTS;
DROP TABLE CIP_AUTHORITY CASCADE CONSTRAINTS;
DROP TABLE CIP_COMMON_CODE CASCADE CONSTRAINTS;
DROP TABLE CIP_MEMBER CASCADE CONSTRAINTS;
DROP TABLE CIP_MENU CASCADE CONSTRAINTS;
DROP TABLE CIP_MULTI_BOARD CASCADE CONSTRAINTS;
DROP TABLE CIP_ORGANIZATION CASCADE CONSTRAINTS;




/* Create Tables */

-- �뙆�씪 �젙蹂�
CREATE TABLE CIP_ATTACHFILE
(
	-- 泥⑤��뙆�씪 �씪�젴踰덊샇
	ATTACHFILE_SEQ varchar2(40) NOT NULL,
	-- �썝蹂몃젅肄붾뱶 UNIQUE SEQ
	SOURCE_UNIQUE_SEQ varchar2(40) NOT NULL,
	-- 泥⑤��뙆�씪 �쑀�삎
	ATTACHFILE_TYPE varchar2(40),
	-- �썝蹂� �뙆�씪紐�
	ORGINALFILE_NAME varchar2(200) NOT NULL,
	-- 泥⑤� �뙆�씪紐�
	PHYSICALFILE_NAME varchar2(200) NOT NULL,
	-- �뜽�꽕�씪 泥⑤��뙆�씪紐�
	THUMBNAIL_NAME varchar2(500),
	-- 泥⑤��뙆�씪 ���옣寃쎈줈
	ATTACHFILE_PATH varchar2(500),
	-- 泥⑤��뙆�씪 �겕湲�
	ATTACHFILE_SIZE number,
	-- �뙆�씪 �넂�씠
	ATTACHFILE_HEIGHT number,
	-- �뙆�씪 �룺
	ATTACHFILE_WIDTH number,
	-- �벑濡앹옄SEQ
	REGISTER_SEQ varchar2(50) NOT NULL,
	-- �벑濡앹씪�옄
	REGISTRY_DATE varchar2(20) NOT NULL,
	-- �닔�젙�옄_SEQ
	MODIFIER_SEQ varchar2(40) NOT NULL,
	-- �닔�젙�씪�옄
	MODIFY_DATE varchar2(20) NOT NULL,
	PRIMARY KEY (ATTACHFILE_SEQ)
);


-- 沅뚰븳 醫낅쪟
CREATE TABLE CIP_AUTHORITY
(
	-- 沅뚰븳 肄붾뱶
	AUTHORITY_ID varchar2(40) NOT NULL,
	-- 紐낆묶
	NAME varchar2(1000) NOT NULL,
	-- 肄붾뱶�꽕紐�
	DESCRIPTION varchar2(1000),
	-- �궗�슜 �뿬遺�
	USE_YN varchar2(40) NOT NULL,
	-- �벑濡앹옄SEQ
	REGISTER_SEQ varchar2(50) NOT NULL,
	-- �벑濡앹씪�옄
	REGISTRY_DATE varchar2(20) NOT NULL,
	-- �닔�젙�옄_SEQ
	MODIFIER_SEQ varchar2(40) NOT NULL,
	-- �닔�젙�씪�옄
	MODIFY_DATE varchar2(20) NOT NULL,
	PRIMARY KEY (AUTHORITY_ID)
);


-- �궗�슜�옄蹂� 沅뚰븳�뱾
CREATE TABLE CIP_AUTHORITY_MEMBER
(
	-- 沅뚰븳 肄붾뱶
	AUTHORITY_ID varchar2(40) NOT NULL,
	-- �쉶�썝_SEQ
	MEMBER_SEQ varchar2(40) NOT NULL,
	-- �벑濡앹옄SEQ
	REGISTER_SEQ varchar2(50) NOT NULL,
	-- �벑濡앹씪�옄
	REGISTRY_DATE varchar2(20) NOT NULL,
	-- �닔�젙�옄_SEQ
	MODIFIER_SEQ varchar2(40) NOT NULL,
	-- �닔�젙�씪�옄
	MODIFY_DATE varchar2(20) NOT NULL,
	UNIQUE (AUTHORITY_ID, MEMBER_SEQ)
);


-- 怨듯넻肄붾뱶
CREATE TABLE CIP_COMMON_CODE
(
	-- 怨듯넻 肄붾뱶_ID
	COMMON_CODE_ID varchar2(40) NOT NULL,
	-- 紐낆묶
	NAME varchar2(1000) NOT NULL,
	-- �젙�젹�닚�꽌
	ORDER_NUMBER number,
	-- �냽�꽦_1
	ATTRIBUTION_1 varchar2(60),
	-- �냽�꽦_2
	ATTRIBUTION_2 varchar2(60),
	-- 肄붾뱶�꽕紐�
	DESCRIPTION varchar2(1000),
	-- 珥덇린 �떆�뒪�뀥 肄붾뱶 �뿬遺�
	SYSTEM_CODE_YN varchar2(40) DEFAULT 'N' NOT NULL,
	-- �궗�슜 �뿬遺�
	USE_YN varchar2(40) NOT NULL,
	-- �긽�쐞 怨듯넻 肄붾뱶 ID
	PARENT_COMMON_CODE_ID varchar2(40),
	-- �벑濡앹옄SEQ
	REGISTER_SEQ varchar2(50) NOT NULL,
	-- �벑濡앹씪�옄
	REGISTRY_DATE varchar2(20) NOT NULL,
	-- �닔�젙�옄_SEQ
	MODIFIER_SEQ varchar2(40) NOT NULL,
	-- �닔�젙�씪�옄
	MODIFY_DATE varchar2(20) NOT NULL,
	PRIMARY KEY (COMMON_CODE_ID)
);


-- �쉶�썝�젙蹂�
CREATE TABLE CIP_MEMBER
(
	-- �쉶�썝_SEQ
	MEMBER_SEQ varchar2(40) NOT NULL,
	-- �쉶�썝 ID
	MEMBER_ID varchar2(50) NOT NULL,
	-- �븫�샇
	PASSWORD varchar2(100) NOT NULL,
	-- �븫�샇�솕�맂 �븫�샇
	CRYPT_PASSWORD varchar2(100),
	-- 紐낆묶
	NAME varchar2(1000) NOT NULL,
	-- EMAIL
	EMAIL varchar2(1000),
	-- �쑕���룿踰덊샇
	CELLPHONE varchar2(20),
	-- �벑濡앹옄SEQ
	REGISTER_SEQ varchar2(50) NOT NULL,
	-- �벑濡앹씪�옄
	REGISTRY_DATE varchar2(20) NOT NULL,
	-- �닔�젙�옄_SEQ
	MODIFIER_SEQ varchar2(40) NOT NULL,
	-- �닔�젙�씪�옄
	MODIFY_DATE varchar2(20) NOT NULL,
	-- 議곗쭅 �씪�젴踰덊샇
	ORGANIZATION_SEQ varchar2(50) NOT NULL,
	PRIMARY KEY (MEMBER_SEQ)
);


-- 硫붾돱 留덉뒪�꽣 �젙蹂�
CREATE TABLE CIP_MENU
(
	-- 硫붾돱 肄붾뱶 SEQ
	MENU_SEQ varchar2(40) NOT NULL,
	-- 紐낆묶
	NAME varchar2(1000) NOT NULL,
	-- �젙�젹�닚�꽌
	ORDER_NUMBER number DEFAULT 1 NOT NULL,
	-- 硫붾돱 二쇱냼
	MENU_URI varchar2(500),
	-- �궗�슜 �뿬遺�
	USE_YN varchar2(40),
	-- �긽�쐞 硫붾돱 肄붾뱶 SEQ
	PARENT_MENU_SEQ varchar2(40),
	-- �벑濡앹옄SEQ
	REGISTER_SEQ varchar2(50) NOT NULL,
	-- �벑濡앹씪�옄
	REGISTRY_DATE varchar2(20) NOT NULL,
	-- �닔�젙�옄_SEQ
	MODIFIER_SEQ varchar2(40) NOT NULL,
	-- �닔�젙�씪�옄
	MODIFY_DATE varchar2(20) NOT NULL,
	PRIMARY KEY (MENU_SEQ)
);


-- 硫붾돱 �뵲瑜� 沅뚰븳
CREATE TABLE CIP_MENU_AUTHORITY
(
	-- 沅뚰븳 肄붾뱶
	AUTHORITY_ID varchar2(40) NOT NULL,
	-- 硫붾돱 肄붾뱶 SEQ
	MENU_SEQ varchar2(40) NOT NULL,
	-- �벑濡앹옄SEQ
	REGISTER_SEQ varchar2(50) NOT NULL,
	-- �벑濡앹씪�옄
	REGISTRY_DATE varchar2(20) NOT NULL,
	-- �닔�젙�옄_SEQ
	MODIFIER_SEQ varchar2(40) NOT NULL,
	-- �닔�젙�씪�옄
	MODIFY_DATE varchar2(20) NOT NULL,
	UNIQUE (AUTHORITY_ID, MENU_SEQ)
);


-- 硫��떚寃뚯떆�뙋
CREATE TABLE CIP_MULTI_BOARD
(
	-- 寃뚯떆臾� �씪�젴踰덊샇
	MULTI_BOARD_SEQ varchar2(40) NOT NULL,
	-- �젣紐�
	TITLE varchar2(4000),
	-- �궡�슜/�뙎湲�
	CONTENT varchar2(4000) NOT NULL,
	-- �떆�옉�씪�떆 (怨듭� �벑)
	START_DATE varchar2(20),
	-- 醫낅즺�씪�떆 (怨듭� �벑)
	END_DATE varchar2(20),
	-- �벑濡앹옄SEQ
	REGISTER_SEQ varchar2(50) NOT NULL,
	-- �벑濡앹씪�옄
	REGISTRY_DATE varchar2(20) NOT NULL,
	-- �닔�젙�옄_SEQ
	MODIFIER_SEQ varchar2(40) NOT NULL,
	-- �닔�젙�씪�옄
	MODIFY_DATE varchar2(20) NOT NULL,
	-- �긽�쐞 寃뚯떆臾� �씪�젴踰덊샇
	PARENT_MULTI_BOARD_SEQ varchar2(40),
	CONSTRAINT PK_MULTI_BOARD PRIMARY KEY (MULTI_BOARD_SEQ)
);


-- 洹몃９/議곗쭅/遺��꽌 援ъ“�룄
CREATE TABLE CIP_ORGANIZATION
(
	-- 議곗쭅 �씪�젴踰덊샇
	ORGANIZATION_SEQ varchar2(50) NOT NULL,
	-- 紐낆묶
	NAME varchar2(1000) NOT NULL,
	-- ���몴 �쟾�솕踰덊샇
	TELEPHONE varchar2(40),
	-- �젙�젹�닚�꽌
	ORDER_NUMBER number,
	-- �긽�쐞 議곗쭅 �씪�젴踰덊샇
	PARENT_ORGANIZATION_SEQ varchar2(50),
	CONSTRAINT PK_ORGANIZATION PRIMARY KEY (ORGANIZATION_SEQ)
);



/* Create Foreign Keys */

ALTER TABLE CIP_AUTHORITY_MEMBER
	ADD FOREIGN KEY (AUTHORITY_ID)
	REFERENCES CIP_AUTHORITY (AUTHORITY_ID)
;


ALTER TABLE CIP_MENU_AUTHORITY
	ADD FOREIGN KEY (AUTHORITY_ID)
	REFERENCES CIP_AUTHORITY (AUTHORITY_ID)
;


ALTER TABLE CIP_COMMON_CODE
	ADD FOREIGN KEY (PARENT_COMMON_CODE_ID)
	REFERENCES CIP_COMMON_CODE (COMMON_CODE_ID)
;


ALTER TABLE CIP_AUTHORITY_MEMBER
	ADD FOREIGN KEY (MEMBER_SEQ)
	REFERENCES CIP_MEMBER (MEMBER_SEQ)
;


ALTER TABLE CIP_MENU
	ADD FOREIGN KEY (PARENT_MENU_SEQ)
	REFERENCES CIP_MENU (MENU_SEQ)
;


ALTER TABLE CIP_MENU_AUTHORITY
	ADD FOREIGN KEY (MENU_SEQ)
	REFERENCES CIP_MENU (MENU_SEQ)
;


ALTER TABLE CIP_MULTI_BOARD
	ADD FOREIGN KEY (PARENT_MULTI_BOARD_SEQ)
	REFERENCES CIP_MULTI_BOARD (MULTI_BOARD_SEQ)
;


ALTER TABLE CIP_MEMBER
	ADD FOREIGN KEY (ORGANIZATION_SEQ)
	REFERENCES CIP_ORGANIZATION (ORGANIZATION_SEQ)
;


ALTER TABLE CIP_ORGANIZATION
	ADD FOREIGN KEY (PARENT_ORGANIZATION_SEQ)
	REFERENCES CIP_ORGANIZATION (ORGANIZATION_SEQ)
;



/* Comments */

COMMENT ON TABLE CIP_ATTACHFILE IS '�뙆�씪 �젙蹂�';
COMMENT ON COLUMN CIP_ATTACHFILE.ATTACHFILE_SEQ IS '泥⑤��뙆�씪 �씪�젴踰덊샇';
COMMENT ON COLUMN CIP_ATTACHFILE.SOURCE_UNIQUE_SEQ IS '�썝蹂몃젅肄붾뱶 UNIQUE SEQ';
COMMENT ON COLUMN CIP_ATTACHFILE.ATTACHFILE_TYPE IS '泥⑤��뙆�씪 �쑀�삎';
COMMENT ON COLUMN CIP_ATTACHFILE.ORGINALFILE_NAME IS '�썝蹂� �뙆�씪紐�';
COMMENT ON COLUMN CIP_ATTACHFILE.PHYSICALFILE_NAME IS '泥⑤� �뙆�씪紐�';
COMMENT ON COLUMN CIP_ATTACHFILE.THUMBNAIL_NAME IS '�뜽�꽕�씪 泥⑤��뙆�씪紐�';
COMMENT ON COLUMN CIP_ATTACHFILE.ATTACHFILE_PATH IS '泥⑤��뙆�씪 ���옣寃쎈줈';
COMMENT ON COLUMN CIP_ATTACHFILE.ATTACHFILE_SIZE IS '泥⑤��뙆�씪 �겕湲�';
COMMENT ON COLUMN CIP_ATTACHFILE.ATTACHFILE_HEIGHT IS '�뙆�씪 �넂�씠';
COMMENT ON COLUMN CIP_ATTACHFILE.ATTACHFILE_WIDTH IS '�뙆�씪 �룺';
COMMENT ON COLUMN CIP_ATTACHFILE.REGISTER_SEQ IS '�벑濡앹옄SEQ';
COMMENT ON COLUMN CIP_ATTACHFILE.REGISTRY_DATE IS '�벑濡앹씪�옄';
COMMENT ON COLUMN CIP_ATTACHFILE.MODIFIER_SEQ IS '�닔�젙�옄_SEQ';
COMMENT ON COLUMN CIP_ATTACHFILE.MODIFY_DATE IS '�닔�젙�씪�옄';
COMMENT ON TABLE CIP_AUTHORITY IS '沅뚰븳 醫낅쪟';
COMMENT ON COLUMN CIP_AUTHORITY.AUTHORITY_ID IS '沅뚰븳 肄붾뱶';
COMMENT ON COLUMN CIP_AUTHORITY.NAME IS '紐낆묶';
COMMENT ON COLUMN CIP_AUTHORITY.DESCRIPTION IS '肄붾뱶�꽕紐�';
COMMENT ON COLUMN CIP_AUTHORITY.USE_YN IS '�궗�슜 �뿬遺�';
COMMENT ON COLUMN CIP_AUTHORITY.REGISTER_SEQ IS '�벑濡앹옄SEQ';
COMMENT ON COLUMN CIP_AUTHORITY.REGISTRY_DATE IS '�벑濡앹씪�옄';
COMMENT ON COLUMN CIP_AUTHORITY.MODIFIER_SEQ IS '�닔�젙�옄_SEQ';
COMMENT ON COLUMN CIP_AUTHORITY.MODIFY_DATE IS '�닔�젙�씪�옄';
COMMENT ON TABLE CIP_AUTHORITY_MEMBER IS '�궗�슜�옄蹂� 沅뚰븳�뱾';
COMMENT ON COLUMN CIP_AUTHORITY_MEMBER.AUTHORITY_ID IS '沅뚰븳 肄붾뱶';
COMMENT ON COLUMN CIP_AUTHORITY_MEMBER.MEMBER_SEQ IS '�쉶�썝_SEQ';
COMMENT ON COLUMN CIP_AUTHORITY_MEMBER.REGISTER_SEQ IS '�벑濡앹옄SEQ';
COMMENT ON COLUMN CIP_AUTHORITY_MEMBER.REGISTRY_DATE IS '�벑濡앹씪�옄';
COMMENT ON COLUMN CIP_AUTHORITY_MEMBER.MODIFIER_SEQ IS '�닔�젙�옄_SEQ';
COMMENT ON COLUMN CIP_AUTHORITY_MEMBER.MODIFY_DATE IS '�닔�젙�씪�옄';
COMMENT ON TABLE CIP_COMMON_CODE IS '怨듯넻肄붾뱶';
COMMENT ON COLUMN CIP_COMMON_CODE.COMMON_CODE_ID IS '怨듯넻 肄붾뱶_ID';
COMMENT ON COLUMN CIP_COMMON_CODE.NAME IS '紐낆묶';
COMMENT ON COLUMN CIP_COMMON_CODE.ORDER_NUMBER IS '�젙�젹�닚�꽌';
COMMENT ON COLUMN CIP_COMMON_CODE.ATTRIBUTION_1 IS '�냽�꽦_1';
COMMENT ON COLUMN CIP_COMMON_CODE.ATTRIBUTION_2 IS '�냽�꽦_2';
COMMENT ON COLUMN CIP_COMMON_CODE.DESCRIPTION IS '肄붾뱶�꽕紐�';
COMMENT ON COLUMN CIP_COMMON_CODE.SYSTEM_CODE_YN IS '珥덇린 �떆�뒪�뀥 肄붾뱶 �뿬遺�';
COMMENT ON COLUMN CIP_COMMON_CODE.USE_YN IS '�궗�슜 �뿬遺�';
COMMENT ON COLUMN CIP_COMMON_CODE.PARENT_COMMON_CODE_ID IS '�긽�쐞 怨듯넻 肄붾뱶 ID';
COMMENT ON COLUMN CIP_COMMON_CODE.REGISTER_SEQ IS '�벑濡앹옄SEQ';
COMMENT ON COLUMN CIP_COMMON_CODE.REGISTRY_DATE IS '�벑濡앹씪�옄';
COMMENT ON COLUMN CIP_COMMON_CODE.MODIFIER_SEQ IS '�닔�젙�옄_SEQ';
COMMENT ON COLUMN CIP_COMMON_CODE.MODIFY_DATE IS '�닔�젙�씪�옄';
COMMENT ON TABLE CIP_MEMBER IS '�쉶�썝�젙蹂�';
COMMENT ON COLUMN CIP_MEMBER.MEMBER_SEQ IS '�쉶�썝_SEQ';
COMMENT ON COLUMN CIP_MEMBER.MEMBER_ID IS '�쉶�썝 ID';
COMMENT ON COLUMN CIP_MEMBER.PASSWORD IS '�븫�샇';
COMMENT ON COLUMN CIP_MEMBER.CRYPT_PASSWORD IS '�븫�샇�솕�맂 �븫�샇';
COMMENT ON COLUMN CIP_MEMBER.NAME IS '紐낆묶';
COMMENT ON COLUMN CIP_MEMBER.EMAIL IS 'EMAIL';
COMMENT ON COLUMN CIP_MEMBER.CELLPHONE IS '�쑕���룿踰덊샇';
COMMENT ON COLUMN CIP_MEMBER.REGISTER_SEQ IS '�벑濡앹옄SEQ';
COMMENT ON COLUMN CIP_MEMBER.REGISTRY_DATE IS '�벑濡앹씪�옄';
COMMENT ON COLUMN CIP_MEMBER.MODIFIER_SEQ IS '�닔�젙�옄_SEQ';
COMMENT ON COLUMN CIP_MEMBER.MODIFY_DATE IS '�닔�젙�씪�옄';
COMMENT ON COLUMN CIP_MEMBER.ORGANIZATION_SEQ IS '議곗쭅 �씪�젴踰덊샇';
COMMENT ON TABLE CIP_MENU IS '硫붾돱 留덉뒪�꽣 �젙蹂�';
COMMENT ON COLUMN CIP_MENU.MENU_SEQ IS '硫붾돱 肄붾뱶 SEQ';
COMMENT ON COLUMN CIP_MENU.NAME IS '紐낆묶';
COMMENT ON COLUMN CIP_MENU.ORDER_NUMBER IS '�젙�젹�닚�꽌';
COMMENT ON COLUMN CIP_MENU.MENU_URI IS '硫붾돱 二쇱냼';
COMMENT ON COLUMN CIP_MENU.USE_YN IS '�궗�슜 �뿬遺�';
COMMENT ON COLUMN CIP_MENU.PARENT_MENU_SEQ IS '�긽�쐞 硫붾돱 肄붾뱶 SEQ';
COMMENT ON COLUMN CIP_MENU.REGISTER_SEQ IS '�벑濡앹옄SEQ';
COMMENT ON COLUMN CIP_MENU.REGISTRY_DATE IS '�벑濡앹씪�옄';
COMMENT ON COLUMN CIP_MENU.MODIFIER_SEQ IS '�닔�젙�옄_SEQ';
COMMENT ON COLUMN CIP_MENU.MODIFY_DATE IS '�닔�젙�씪�옄';
COMMENT ON TABLE CIP_MENU_AUTHORITY IS '硫붾돱 �뵲瑜� 沅뚰븳';
COMMENT ON COLUMN CIP_MENU_AUTHORITY.AUTHORITY_ID IS '沅뚰븳 肄붾뱶';
COMMENT ON COLUMN CIP_MENU_AUTHORITY.MENU_SEQ IS '硫붾돱 肄붾뱶 SEQ';
COMMENT ON COLUMN CIP_MENU_AUTHORITY.REGISTER_SEQ IS '�벑濡앹옄SEQ';
COMMENT ON COLUMN CIP_MENU_AUTHORITY.REGISTRY_DATE IS '�벑濡앹씪�옄';
COMMENT ON COLUMN CIP_MENU_AUTHORITY.MODIFIER_SEQ IS '�닔�젙�옄_SEQ';
COMMENT ON COLUMN CIP_MENU_AUTHORITY.MODIFY_DATE IS '�닔�젙�씪�옄';
COMMENT ON TABLE CIP_MULTI_BOARD IS '硫��떚寃뚯떆�뙋';
COMMENT ON COLUMN CIP_MULTI_BOARD.MULTI_BOARD_SEQ IS '寃뚯떆臾� �씪�젴踰덊샇';
COMMENT ON COLUMN CIP_MULTI_BOARD.TITLE IS '�젣紐�';
COMMENT ON COLUMN CIP_MULTI_BOARD.CONTENT IS '�궡�슜/�뙎湲�';
COMMENT ON COLUMN CIP_MULTI_BOARD.START_DATE IS '�떆�옉�씪�떆 (怨듭� �벑)';
COMMENT ON COLUMN CIP_MULTI_BOARD.END_DATE IS '醫낅즺�씪�떆 (怨듭� �벑)';
COMMENT ON COLUMN CIP_MULTI_BOARD.REGISTER_SEQ IS '�벑濡앹옄SEQ';
COMMENT ON COLUMN CIP_MULTI_BOARD.REGISTRY_DATE IS '�벑濡앹씪�옄';
COMMENT ON COLUMN CIP_MULTI_BOARD.MODIFIER_SEQ IS '�닔�젙�옄_SEQ';
COMMENT ON COLUMN CIP_MULTI_BOARD.MODIFY_DATE IS '�닔�젙�씪�옄';
COMMENT ON COLUMN CIP_MULTI_BOARD.PARENT_MULTI_BOARD_SEQ IS '�긽�쐞 寃뚯떆臾� �씪�젴踰덊샇';
COMMENT ON TABLE CIP_ORGANIZATION IS '洹몃９/議곗쭅/遺��꽌 援ъ“�룄';
COMMENT ON COLUMN CIP_ORGANIZATION.ORGANIZATION_SEQ IS '議곗쭅 �씪�젴踰덊샇';
COMMENT ON COLUMN CIP_ORGANIZATION.NAME IS '紐낆묶';
COMMENT ON COLUMN CIP_ORGANIZATION.TELEPHONE IS '���몴 �쟾�솕踰덊샇';
COMMENT ON COLUMN CIP_ORGANIZATION.ORDER_NUMBER IS '�젙�젹�닚�꽌';
COMMENT ON COLUMN CIP_ORGANIZATION.PARENT_ORGANIZATION_SEQ IS '�긽�쐞 議곗쭅 �씪�젴踰덊샇';



